version: "3.1"

services:
  bot:
    image: schedule_bot
    build: .
    container_name: 'schedule_bot'
    restart: always
    command: bash -c "python3 /code/app.py"
    volumes:
      - .:/code
    env_file:
      - .env